// <auto-generated />
namespace DCC_TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class employeeupdatedmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employeeupdatedmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201807130126241_employee updated migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
